#!/bin/bash

# List installed packages that nothing depends on
# See: https://wiki.archlinux.org/index.php/Pacman_Tips#Listing_all_packages_that_nothing_else_depends_on

expac "%n %N" -Q $(expac "%n %G" | grep -v ' base') | awk '$2 == "" {print $1}'
